# Generated by Django 4.0.3 on 2022-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrestaurantstack',
            name='weekly_restaurants_stack',
        ),
        migrations.AddField(
            model_name='userrestaurantstack',
            name='weekly_restaurant_picks',
            field=models.ManyToManyField(blank=True, to='restaurants.restaurant'),
        ),
    ]
