# Generated by Django 4.0.3 on 2022-03-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userrestaurantpick_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrestaurantpick',
            old_name='created_at',
            new_name='created_at_week_num',
        ),
    ]
