# Generated by Django 4.0.3 on 2022-03-21 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userrestaurantpick_created_at_week_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurantpick',
            name='created_at_week_num',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
